# Generated by Django 3.0.5 on 2020-04-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=1024, null=True)),
                ('auth_token', models.CharField(default=None, max_length=1024, null=True)),
                ('token', models.CharField(blank=True, max_length=1024, null=True)),
                ('phone_number', models.CharField(default='0000000000', max_length=30, unique=True)),
                ('password', models.CharField(default='testpwd1', max_length=1024, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TOY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField()),
                ('seen', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='v1.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='v1.User')),
            ],
        ),
    ]
