# Generated by Django 3.0.5 on 2020-04-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default='bj1PRBXG0reGNTj4icTRB1EvKeXXDF13ZYI6MYLTgjRIvIMJpce_tJFZJWOu3jbzK3ZIULPd5hly9WkipD62fQ', max_length=1024),
        ),
    ]
