# Generated by Django 3.0.5 on 2020-04-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20200413_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
