# Generated by Django 3.0.5 on 2020-04-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=30, primary_key=True, serialize=False),
        ),
    ]
